### ISSUE TITLE
Zurück aus Vorschau

### ISSUE THREAD

**Issue by mic-men** [mic-men/es-test-8#5]
Da man sich in der Vorschau durch verschiedenen Relationsbeziehungen klicken kann, wäre es wünschenswert, wenn es eine Möglichkeit gäbe, direkt zur Suchumgebung zurück zu kommen. Der _Zurück_ - Knopf geht immer nur zur vorhergehenden Seite.

**Comment by mic-men** [comment]
Ergänzung: Beim Klick auf Objekte, die in Beziehung stehen, wird ein neuer Browser-Tab geöffnet. Insofern stimmt das oben beschriebene so nicht (mehr).
Kommt man über einen anderweitg erhaltenen Link, z.B. auch Handle, auf die Vorschau-Seite eines Objekts, ist **ab Version 8** der _Zurück_-Button in der ES-Vorschauseite nicht mehr funktionslos, sondern eröffnet die Möglichkeit in andere Umgebungen, zumeist die Suchumgebung, zu wechseln. Damit würde ich das Problem als gelöst betrachten. Bitte um Kommentare, falls das anders gesehen wird.

**Comment by mic-men** [comment]
Die oben genannte Funktionalität/Lösung ist in Version **8.0** enthalten, ging in der anfänglichen Version 8.1 aber verloren. Ab Version **8.1.0-RC4** ist sie wieder enthalten.

**Comment by VCRP-fetzer** [comment]
Es sei ergänzt, dass der Zurück-Button weiterhin dann nicht funktioniert, wenn man den Link aus der Zwischenablage in die Adresszeile des Browsers einfügt und aufruft.
